import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatDate, formatCurrency, calculateDeduction, FUEL_TYPE_LABELS } from './constants'

export function generateLogbookPDF({ user, vehicle, period, trips }) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20

  // Cover page
  doc.setFontSize(24)
  doc.setTextColor(26, 39, 68) // navy
  doc.text('Vehicle Logbook', pageWidth / 2, 40, { align: 'center' })
  doc.setFontSize(14)
  doc.setTextColor(34, 197, 94) // accent
  doc.text('IRD Compliant Record', pageWidth / 2, 52, { align: 'center' })

  doc.setFontSize(11)
  doc.setTextColor(60, 60, 60)

  const totalKm = period.end_odometer - period.start_odometer
  const businessTrips = trips.filter(t => t.trip_type === 'business')
  const privateTrips = trips.filter(t => t.trip_type === 'private')
  const businessKm = businessTrips.reduce((sum, t) => sum + t.distance_km, 0)
  const privateKm = privateTrips.reduce((sum, t) => sum + t.distance_km, 0)
  const businessPct = totalKm > 0 ? ((businessKm / totalKm) * 100).toFixed(1) : '0.0'

  const details = [
    ['Owner', user.name || user.email],
    ['Vehicle', `${vehicle.year} ${vehicle.make} ${vehicle.model}`],
    ['Registration', vehicle.registration || 'N/A'],
    ['Fuel Type', FUEL_TYPE_LABELS[vehicle.fuel_type] || vehicle.fuel_type],
    ['', ''],
    ['Logbook Period', `${formatDate(period.start_date)} to ${formatDate(period.end_date)}`],
    ['Opening Odometer', `${period.start_odometer.toLocaleString()} km`],
    ['Closing Odometer', `${period.end_odometer.toLocaleString()} km`],
    ['Total Distance', `${totalKm.toLocaleString()} km`],
    ['', ''],
    ['Total Business km', `${businessKm.toLocaleString()} km`],
    ['Total Private km', `${privateKm.toLocaleString()} km`],
    ['Business Use Percentage', `${businessPct}%`],
    ['Valid Until', period.valid_until ? formatDate(period.valid_until) : 'N/A'],
  ]

  let y = 70
  details.forEach(([label, value]) => {
    if (label === '') { y += 4; return }
    doc.setFont(undefined, 'bold')
    doc.text(label + ':', margin, y)
    doc.setFont(undefined, 'normal')
    doc.text(value, margin + 65, y)
    y += 8
  })

  // Trip log table
  doc.addPage()
  doc.setFontSize(16)
  doc.setTextColor(26, 39, 68)
  doc.text('Trip Log', margin, 20)

  const tableData = trips.map(t => [
    formatDate(t.date),
    t.start_odometer.toLocaleString(),
    t.end_odometer.toLocaleString(),
    `${t.distance_km.toFixed(1)} km`,
    t.trip_type === 'business' ? (t.destination || '') : '',
    t.trip_type === 'business' ? (t.purpose || '') : '',
    t.trip_type === 'business' ? 'B' : 'P',
  ])

  autoTable(doc, {
    startY: 28,
    head: [['Date', 'Start Odo', 'End Odo', 'Distance', 'Destination', 'Purpose', 'Type']],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [26, 39, 68], textColor: 255 },
    columnStyles: {
      0: { cellWidth: 22 },
      4: { cellWidth: 30 },
      5: { cellWidth: 30 },
      6: { cellWidth: 12, halign: 'center' },
    },
    margin: { left: margin, right: margin },
  })

  // Summary page
  doc.addPage()
  doc.setFontSize(16)
  doc.setTextColor(26, 39, 68)
  doc.text('Summary', margin, 20)

  doc.setFontSize(11)
  doc.setTextColor(60, 60, 60)

  const deduction = calculateDeduction(businessKm, totalKm, vehicle.fuel_type)

  const summaryLines = [
    `Business Use Percentage: ${businessPct}%`,
    `Calculation: ${businessKm.toLocaleString()} business km / ${totalKm.toLocaleString()} total km x 100`,
    '',
    'Estimated Deduction (Kilometre Rate Method):',
    `  Tier 1: ${deduction.tier1BusinessKm.toLocaleString()} km x ${formatCurrency(deduction.rates.tier1)}/km = ${formatCurrency(deduction.tier1Amount)}`,
    `  Tier 2: ${deduction.tier2BusinessKm.toLocaleString()} km x ${formatCurrency(deduction.rates.tier2)}/km = ${formatCurrency(deduction.tier2Amount)}`,
    `  Total Estimated Deduction: ${formatCurrency(deduction.totalDeduction)}`,
  ]

  y = 34
  summaryLines.forEach(line => {
    doc.text(line, margin, y)
    y += line === '' ? 4 : 7
  })

  // Disclaimer
  y += 10
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  const disclaimer = 'This logbook has been kept in accordance with IRD requirements for vehicle expense claims. Refer to ird.govt.nz/vehicle-expenses for current rates and requirements. This document does not constitute tax advice.'
  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - margin * 2)
  doc.text(disclaimerLines, margin, y)

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      'Generated by Klicks (klicks.nz) \u2014 built by Mini Robot (mini-robot.nz)',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  return doc
}
